/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminDealReportsRouteImport } from './routes/admin.deal-reports'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminVehiclesVehicleIdRouteImport } from './routes/admin.vehicles.$vehicleId'

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealReportsRoute = AdminDealReportsRouteImport.update({
  id: '/admin/deal-reports',
  path: '/admin/deal-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/admin/brands',
  path: '/admin/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesVehicleIdRoute = AdminVehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => AdminVehiclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/deal-reports': typeof AdminDealReportsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/vehicles/$vehicleId': typeof AdminVehiclesVehicleIdRoute
}
export interface FileRoutesByTo {
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/deal-reports': typeof AdminDealReportsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/vehicles/$vehicleId': typeof AdminVehiclesVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/deal-reports': typeof AdminDealReportsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/vehicles/$vehicleId': typeof AdminVehiclesVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin/brands'
    | '/admin/deal-reports'
    | '/admin/promotions'
    | '/admin/vehicles'
    | '/admin/'
    | '/admin/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/brands'
    | '/admin/deal-reports'
    | '/admin/promotions'
    | '/admin/vehicles'
    | '/admin'
    | '/admin/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/admin/brands'
    | '/admin/deal-reports'
    | '/admin/promotions'
    | '/admin/vehicles'
    | '/admin/'
    | '/admin/vehicles/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminDealReportsRoute: typeof AdminDealReportsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminVehiclesRoute: typeof AdminVehiclesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deal-reports': {
      id: '/admin/deal-reports'
      path: '/admin/deal-reports'
      fullPath: '/admin/deal-reports'
      preLoaderRoute: typeof AdminDealReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles/$vehicleId': {
      id: '/admin/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/admin/vehicles/$vehicleId'
      preLoaderRoute: typeof AdminVehiclesVehicleIdRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
  }
}

interface AdminVehiclesRouteChildren {
  AdminVehiclesVehicleIdRoute: typeof AdminVehiclesVehicleIdRoute
}

const AdminVehiclesRouteChildren: AdminVehiclesRouteChildren = {
  AdminVehiclesVehicleIdRoute: AdminVehiclesVehicleIdRoute,
}

const AdminVehiclesRouteWithChildren = AdminVehiclesRoute._addFileChildren(
  AdminVehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminDealReportsRoute: AdminDealReportsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminVehiclesRoute: AdminVehiclesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
